### ISSUE TITLE
Does not download all photos

### ISSUE THREAD

**Issue by hubert3** [bylexus/gphotos-sync#1]
Trying to download a few hundred photos in an album shared with me, the tool only downloads 101 unique files and seems to loop through the same filenames repeatedly in batches

```
Working on Batch 1, item 4...
   Filename: IMG_6124.HEIC
Downloading IMG_6124.HEIC to /Users/hubert/Downloads/gphotos/2023/IMG_6124.HEIC

...

Working on Batch 13, item 1204...
   Filename: IMG_6124.HEIC
Downloading IMG_6124.HEIC to /Users/hubert/Downloads/gphotos/2023/IMG_6124.HEIC
Working on Batch 13, item 1205...
```

**Comment by bylexus** [comment]
Thanks for the input. This little tool is still in an experimental phase, there is a high possibility that there is a bug there.
I'll have a look at it.

**Comment by bylexus** [comment]
Just as a note, commit https://github.com/bylexus/gphotos-sync/commit/50da876d2d143628eac925915b888c49f882eb36 fixes this problem hopefully.
